movie/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
app_name="app1"
urlpatterns = [
    # path('',views.home,name="home"),
    #class calling
    path('',views.Home.as_view(),name="home"),
    # path('add',views.addmovie,name="add"),
    # path('add1',views.addmovie1,name="add1"),
    path('add1',views.Addmovie.as_view(),name="add1"),
    # path('detail/<int:i>', views.detail, name="detail"),
    path('detail/<int:pk>',views.Detail.as_view(),name="detail"),

    # path('edit/<int:a>',views.edit,name="edit"),
    path('edit/<int:pk>',views.Edit.as_view(),name="edit"),
    # path('delete/<int:p>',views.delete,name="delete"),
    path('delete/<int:pk>',views.Delete.as_view(),name="delete"),
]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    year=models.IntegerField()
    language=models.CharField(max_length=20)
    image=models.ImageField(upload_to="img",blank=True,null=True)

    def __str__(self):
        return self.title

movie/app1/forms.py
from django import forms
from app1.models import Movie




class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'# otherwise['title','description']

movie/app1/views.py
from django.shortcuts import render,redirect
from app1.models import Movie
from app1.forms import MovieForm
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView


# Create your views here.
#function based
# def home(request):
#
#     k=Movie.objects.all()
#     return render(request, 'home.html',{'movie':k})
# class based
class Home(ListView):
    model=Movie
    template_name="home.html"
    context_object_name="movie"

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     queryset = qs.filter(name__startswith="a")
    #     return queryset


     # def get_context_data(self):
     #     context=super().get_context_data()
     #     context['name']="arun"
     #     context['age']="34"
     #     return context
    # extra_context = {'name':'arun','age':21}
class Addmovie(CreateView):
    model=Movie
    fields=['title','description','year','image','language']
    template_name='add1.html'
    success_url=reverse_lazy('app1:home')
# def addmovie1(request):
#     if(request.method=="POST"):
#         form=MovieForm(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return home(request)
#
#     form=MovieForm()
#     context={'form':form}
#     return render(request,'add1.html',context)
# def addmovie(request):
#     if(request.method=="POST"):
#         t=request.POST['t']
#         d=request.POST['d']
#         y=request.POST['y']
#         l=request.POST['l']
#         i=request.FILES['i']
#
#         m=Movie.objects.create(title=t,description=d,year=y,language=l,image=i)
#         m.save()
#         return home(request)
#
#
#
#     return render(request, 'add.html')
# def detail(request,i):
#     k=Movie.objects.get(id=i)
#     return render(request,'detail.html',{'movie':k})

class Detail(DetailView):
    model=Movie
    template_name="detail.html"
    context_object_name="movie"

# def edit(request,a):
#     k=Movie.objects.get(id=a)
#     if(request.method=="POST"):
#         k.title=request.POST['t']
#         k.description=request.POST['d']
#         k.year=request.POST['y']
#         k.language=request.POST['l']
#         if(request.FILES.get('i')==None):
#             k.save()
#         else:
#             k.image=request.FILES['i']
#
#         k.save()
#         return home(request)
#
#     return render(request,'edit.html',{'movie':k})
class Edit(UpdateView):
    model = Movie
    fields = ['title', 'description', 'year', 'image', 'language']
    template_name = 'edit.html'
    success_url = reverse_lazy('app1:home')


# def delete(request,p):
#     k = Movie.objects.get(id=p)
#     k.delete()
#     return home(request)

class Delete(DeleteView):
    template_name="delete.html"
    model=Movie
    success_url=reverse_lazy('app1:home')

movie/templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center">addmovie</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="Enter the title">
</div>
       <div class="mb-3">
  <label class="form-label">description</label>
  <input type="text" class="form-control"  name="d" placeholder="Enter the description">
</div>
         <div class="mb-3">
  <label class="form-label">year</label>
  <input type="number" class="form-control"  name="y" placeholder="Enter the year">
</div>
          <div class="mb-3">
  <label class="form-label">language</label>
  <input type="text" class="form-control"  name="l" placeholder="Enter the language">
</div>

    <div class="mb-3">
  <label class="form-label">image</label>
  <input type="file" class="form-control"  name="i">
</div>

   <div class="mb-3">
       <input type="submit" value="ADD">
   </div>

</form>

{% endblock %}

movie/templates/add1.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
{{form}}
        </table>
    <input type="submit">
</form>


{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">moviestore</a>
    <form class="d-flex" role="search">


      <a class="btn btn-outline-success" href="{% url 'app1:add1' %}">add movies</a>


    </form>
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
{{form}}
        </table>
    <h2>are you sure u want to delete?</h2>
    <input type="Delete">
</form>


{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card mb-3 mt-3 mx-auto" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4 me-6">
      <img src="{{movie.image.url}}" class="rounded-start p-3" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body text-success">
        <h5 class="card-title">Title : {{movie.title}}</h5>
        <p class="card-text">description : {{movie.description}}</p>
        <p class="card-text">Language : {{movie.language}}</p>
          <p class="card-text">year : {{movie.year}}</p>
        <a href="{% url 'app1:edit' movie.id %}" class="btn btn-success">edit</a>
         <a href="{% url 'app1:delete' movie.id %}" class="btn btn-success">delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center">addmovie</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
<!--  <label class="form-label">Title</label>-->
<!--  <input type="text" class="form-control" name="t" value="{{movie.title}}" placeholder="Enter the title">-->
<!--</div>-->
<!--       <div class="mb-3">-->
<!--  <label class="form-label">description</label>-->
<!--  <input type="text" class="form-control"  name="d" value="{{movie.description}}" placeholder="Enter the description">-->
<!--</div>-->
<!--         <div class="mb-3">-->
<!--  <label class="form-label">year</label>-->
<!--  <input type="number" class="form-control"  name="y" value="{{movie.year}}"  placeholder="Enter the year">-->
<!--</div>-->
<!--          <div class="mb-3">-->
<!--  <label class="form-label">language</label>-->
<!--  <input type="text" class="form-control"  name="l" value="{{movie.language}}" placeholder="Enter the language">-->
<!--</div>-->

<!--    <div class="mb-3">-->
<!--  <label class="form-label">image</label>-->
<!--        <img src="{{movie.image.url}}">-->
<!--  <input type="file" class="form-control"  name="i">-->
<!--</div>-->
   {% csrf_token %}
    <table>
{{form}}
        </table>



   <div class="mb-3">
       <input type="submit" value="ADD">
   </div>

</form>

{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        {% for i in movie %}
        <div class="col-sm-4 mt-3"><div class="card mb-2" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.title}}</h5>
    <p class="card-text">{{i.description}}</p>
      <p class="card-text">{{i.year}}</p>
    <a href="{% url 'app1:detail' i.id %}" class="btn btn-success">details</a>
  </div>
</div></div>


        {% endfor %}

 </div>

</div>


{% endblock %}